name: 🚀 Deploy SMSWithoutBorders Visibility Dashboard on Server (production)
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: 🚀 Execute Deployment Script on Server
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://telemetry.smswithoutborders.com
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      
      - name: Create .env.local file, install and build
        run: |
            echo "RELIABILITY_URL=${{ vars.RELIABILITY_URL }}" > .env.local
            echo "RESILIENCE_URL=${{ vars.RESILIENCE_URL }}" >> .env.local
            yarn install
            yarn build

      - name: Securely Copy Artifacts to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "build/*"
          target: "${{ secrets.BUILD_PATH }}"
          strip_components: 1
          rm: true

      - name: 🚀 Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            set -e

            echo "============================"
            echo "🚀 Deploy Project ..."
            echo "============================"
            if ! ${{secrets.BUILD_CMD}}; then
              echo "❌ Error deploying project!"
              exit 1
            fi
            echo "==============================="
            echo "✅ Deployment complete"
            echo "==============================="
